# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2810561d9258767dd65e89acf9d7fea3cfe6bd65418ff78a697af3f95add532773b337a139a0b7fdf37f00e0297affa3e00726b46d43a3e3b29dd56680ca0c

test:
  secret_key_base: e4d2004f8dd051c58279f43789555892f201dd6b7f8b118d924008a7cb0c83c1ac7ca0a838b5975f19c214f97452b7d59a32543c44d4b4a67ef80377f7dd13f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
